#!/bin/bash

# Look for running LaunchDaemon
ldIsRunning=`launchctl list | grep com.ironsystems.flipswitch | awk '{print $3}'`

# If LaunchDaemon is running, unload LaunchDaemon
if [ "$ldIsRunning" == "com.ironsystems.flipswitch" ]; then
        echo "LaunchDaemon found running"
        launchctl unload /Library/LaunchDaemons/com.ironsystems.flipswitch.plist
        echo "LaunchDaemon has been unloaded"
fi

# If LaunchDaemon is installed, remove LaunchDaemon
ldIsInstalled=`ls /Library/LaunchDaemons/ | grep com.ironsystems.flipswitch.plist`

if [ "$ldIsInstalled" == "com.ironsystems.flipswitch.plist" ]; then
        echo "Previous LaunchDaemon was installed"
        rm -r /Library/LaunchDaemons/com.ironsystems.flipswitch.plist
        echo "Previous LaunchDaemon has been removed"
fi

# If flipswitch is installed, remove flipswitch
fsIsInstalled=`ls /Library/ironsystems/bin/ | grep flipswitch`

if [ "$fsIsInstalled" == "flipswitch*" ]; then
        echo "Previous version of flipswitch was installed"
        rm -r /Library/ironsystems/bin/flipswitch*
        echo "Previous version of flipswitch has been removed"
fi
