#!/bin/bash

# Look for running LaunchDaemon
ldIsRunning=`launchctl list | grep ca.sonofiron.oneConnection | awk '{print $3}'`

# If LaunchDaemon is running, unload LaunchDaemon
if [ "$ldIsRunning" == "ca.sonofiron.oneConnection" ]; then
        echo "LaunchDaemon found running"
        launchctl unload /Library/LaunchDaemons/ca.sonofiron.oneConnection.plist
        echo "LaunchDaemon has been unloaded"
fi

# If LaunchDaemon is installed, remove LaunchDaemon
ldIsInstalled=`ls /Library/LaunchDaemons/ | grep ca.sonofiron.oneConnection.plist`

if [ "$ldIsInstalled" == "ca.sonofiron.oneConnection.plist" ]; then
        echo "Previous LaunchDaemon was installed"
        rm -r /Library/LaunchDaemons/ca.sonofiron.oneConnection.plist
        echo "Previous LaunchDaemon has been removed"
fi

# If oneConnection is installed, remove oneConnection
if [ -f "/Library/oneConnection/bin/oneConnection" ]; then
        echo "Previous version of oneConnection was installed"
        rm -r /Library/oneConnection/bin/oneConnection*
        echo "Previous version of oneConnection has been removed"
fi
